CREATE DATABASE `penly-db` DEFAULT CHARACTER SET `utf8` DEFAULT COLLATE `utf8_hungarian_ci`;

GRANT USAGE ON *.* TO `penly-app`@`%` IDENTIFIED BY PASSWORD '*D02E2BED972E299484B5439FBB650A8B608BF86C';

GRANT ALL PRIVILEGES ON `penly-db`.* TO `penly-app`@`%` WITH GRANT OPTION;