### Poszt létrehozása (PUT)

PUT http://localhost:3524/poszt
Content-Type: application/json

{
    "felhasznaloId": 2,
    "tartalom": "sanyne vedd fel"
}

### Posztok lekérése (GET)

GET http://localhost:3524/poszt

### Poszt lekérése id-alapján (GET)

GET http://localhost:3524/poszt/20

### Poszt törlése id alapján (DELETE)

DELETE  http://localhost:3524/poszt/1


### Poszt módosítása id alapján (PATCH)

PATCH  http://localhost:3524/poszt/4
Content-Type: application/json

{
    "felhasznaloID": 2,
    "tartalom": "ne vedd fel"
}