###(PUT /api/dolgozo)  Új dolgozó felvétele
PUT http://localhost:3000/api/dolgozo
Content-Type: application/json

{
    "vezeteknev": "Nemezis",
    "keresztnev": "Edit",
    "szul_hely": "Nyiregyhaza",
    "szul_datum": "1990-05-01",
    "adoszam": 1122334455,
    "TAJ_szam": 564325798,
    "lakhely": "Linz",
    "telefonszam": 208982587,
    "email": "nemezisedits@ganyolda.com",
    "ertesitesi_nev": "Selim Etkar",
    "ertesitesi_telefonszam": 987654321,
    "ertesitendo_jelleg": "Gyah",
    "statusz": true,
    "szerzodes_tipusa": true,
    "munkakor": "Ellenség"
}

###(GET /api/dolgozo) Minden dolgozó kilistázása
GET http://localhost:3000/api/dolgozo
Content-Type: application/json

###(GET /api/dolgozo/:id) Egy dolgozó kilistázása ID alapján
GET http://localhost:3000/api/dolgozo/5
Content-Type: application/json

###(PATCH /api/dolgozo/:id) Dolgozó adatainak módosítása
PATCH http://localhost:3000/api/dolgozo/2
Content-Type: application/json

{
    "vezeteknev": "Nemezis Updated",
    "keresztnev": "Edit Updated",
    "szul_hely": "Nyiregyhaza Updated",
    "szul_datum": "1990-05-01",
    "adoszam": 1122334455,
    "TAJ_szam": 564325798,
    "lakhely": "Linz Updated",
    "telefonszam": 208982587,
    "email": "nemezisedits@ganyolda.com",
    "ertesitesi_nev": "Selim Etkar Updated",
    "ertesitesi_telefonszam": 987654321,
    "ertesitendo_jelleg": "Gyah Updated",
    "statusz": false,
    "szerzodes_tipusa": false,
    "munkakor": "Ellenség Updated"
}

###(DELETE /api/dolgozo/:id) Dolgozó törlése
DELETE http://localhost:3000/api/dolgozo/2
Content-Type: application/json

###(PUT /api/dolgozo) Dolgozó felvétele hiányzó adatokkal
PUT http://localhost:3000/api/dolgozo
Content-Type: application/json

{
    "vezeteknev": "Nemezis",
    "keresztnev": "Edit"
}

###(PUT /api/dolgozo) Dolgozó felvétele duplikált email címmel
PUT http://localhost:3000/api/dolgozo
Content-Type: application/json

{
    "vezeteknev": "Nemezis",
    "keresztnev": "Edit",
    "szul_hely": "Nyiregyhaza",
    "szul_datum": "1990-05-01",
    "adoszam": 1122334455,
    "TAJ_szam": 564325798,
    "lakhely": "Linz",
    "telefonszam": 208982587,
    "email": "nemezisedit@ganyolda.com",
    "ertesitesi_nev": "Selim Etkar",
    "ertesitesi_telefonszam": 987654321,
    "ertesitendo_jelleg": "Gyah",
    "statusz": true,
    "szerzodes_tipusa": true,
    "munkakor": "Ellenség"
}

###(PUT /api/dolgozo/:id/szabadsag) Szabadság igénylés

PUT http://localhost:3000/api/dolgozo/926/szabadsag
Content-Type: application/json

{
   "kezdete": "2021-06-01",
   "vege": "2021-06-05",
   "oka": "Műtét"
}